In [18]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from scipy.stats import entropy
import numpy as np
# import pandas as pd
import matplotlib.pyplot as plt
import time
import socket, struct

import imblearn
from imblearn.under_sampling import RandomUnderSampler
from sklearn.preprocessing import LabelEncoder
from collections import Counter
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import make_pipeline
from imblearn.under_sampling import NearMiss
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.utils import class_weight
import tensorflow as tf
import tensorflow_probability as tfp
import numpy as np
from scipy.spatial.distance import jensenshannon
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report
import os

In [19]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.distributions import Normal
import numpy as np

In [20]:
import os

# Getting all the arff files from the current directory
files = [arff for arff in os.listdir('.') if arff.endswith(".arff")]

# Function for converting arff list to csv list
def toCsv(text):
    data = False
    header = ""
    new_content = []
    for line in text:
        if not data:
            if "@ATTRIBUTE" in line or "@attribute" in line:
                attributes = line.split()
                if("@attribute" in line):
                    attri_case = "@attribute"
                else:
                    attri_case = "@ATTRIBUTE"
                column_name = attributes[attributes.index(attri_case) + 1]
                header = header + column_name + ","
            elif "@DATA" in line or "@data" in line:
                data = True
                header = header[:-1]
                header += '\n'
                new_content.append(header)
        else:
            new_content.append(line)
    return new_content


# Main loop for reading and writing files
for file in files:
    with open(file, "r") as inFile:
        content = inFile.readlines()
        name, ext = os.path.splitext(inFile.name)
        new = toCsv(content)
        with open(name + ".csv", "w") as outFile:
            outFile.writelines(new)

In [21]:
df1=pd.read_csv('TimeBasedFeatures-Dataset-30s-AllinOne.csv')

In [22]:
df2=pd.read_csv('TimeBasedFeatures-Dataset-30s.csv')

In [23]:
df1.head()

duration  total_fiat  total_biat  min_fiat  min_biat       max_fiat  \
0  22930417          18           4  10995965  10960941  314115.301370   
1  25199304          16           4  11037969  10851858  359269.900000   
2  29772995          17           7   4093396   3956161  261815.256637   
3  29609149          22           6   3954677   3943698  271180.963303   
4   7863522          30           8   2067690   2068091  244213.125000   

        max_biat     mean_fiat     mean_biat  flowPktsPerSecond  ...  \
0  360993.158730  1.306745e+06  1.389355e+06           6.018207  ...   
1  387414.676923  1.373362e+06  1.392885e+06           5.436658  ...   
2  310135.364583  6.445422e+05  6.512717e+05           7.086959  ...   
3  287136.446602  6.685474e+05  6.590460e+05           7.227496  ...   
4  252051.483871  5.718062e+05  5.628123e+05           8.266016  ...   

     std_flowiat  min_active   mean_active  max_active    std_active  \
0  952994.511204     1491627  5.011278e+06    11141326  4.507600e+06   
1  976395.388090     1710925  4.164396e+06    14269600  4.973926e+06   
2  462297.947930     1363299  2.706523e+06     6192566  1.445372e+06   
3  472527.270988     1443143  2.937555e+06     4176130  8.769669e+05   
4  400581.170736     2092947  2.535199e+06     3282729  6.509928e+05   

   min_idle     mean_idle  max_idle      std_idle  class1  
0   1079974  3.668800e+06  10945954  4.855368e+06    CHAT  
1   1234883  3.150269e+06  10851858  3.797336e+06    CHAT  
2   1147658  1.955468e+06   3956161  8.938483e+05    CHAT  
3   1065834  2.022585e+06   3895269  9.303813e+05    CHAT  
4   1707343  1.897912e+06   2017289  1.667869e+05    CHAT  

[5 rows x 24 columns]

In [24]:
df1.columns.size

24

In [25]:
df2.columns.size

24

In [26]:
df2.head()

duration  total_fiat  total_biat  min_fiat  min_biat       max_fiat  \
0  22930417          18           4  10995965  10960941  314115.301370   
1  25199304          16           4  11037969  10851858  359269.900000   
2  29772995          17           7   4093396   3956161  261815.256637   
3  29609149          22           6   3954677   3943698  271180.963303   
4   7863522          30           8   2067690   2068091  244213.125000   

        max_biat     mean_fiat     mean_biat  flowPktsPerSecond  ...  \
0  360993.158730  1.306745e+06  1.389355e+06           6.018207  ...   
1  387414.676923  1.373362e+06  1.392885e+06           5.436658  ...   
2  310135.364583  6.445422e+05  6.512717e+05           7.086959  ...   
3  287136.446602  6.685474e+05  6.590460e+05           7.227496  ...   
4  252051.483871  5.718062e+05  5.628123e+05           8.266016  ...   

     std_flowiat  min_active   mean_active  max_active    std_active  \
0  952994.511204     1491627  5.011278e+06    11141326  4.507600e+06   
1  976395.388090     1710925  4.164396e+06    14269600  4.973926e+06   
2  462297.947930     1363299  2.706523e+06     6192566  1.445372e+06   
3  472527.270988     1443143  2.937555e+06     4176130  8.769669e+05   
4  400581.170736     2092947  2.535199e+06     3282729  6.509928e+05   

   min_idle     mean_idle  max_idle      std_idle  class1  
0   1079974  3.668800e+06  10945954  4.855368e+06    CHAT  
1   1234883  3.150269e+06  10851858  3.797336e+06    CHAT  
2   1147658  1.955468e+06   3956161  8.938483e+05    CHAT  
3   1065834  2.022585e+06   3895269  9.303813e+05    CHAT  
4   1707343  1.897912e+06   2017289  1.667869e+05    CHAT  

[5 rows x 24 columns]

In [27]:
X = df1[df1.columns[:-1]]
y = df1['class1']

# Scale the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Encode the labels
encoder = LabelEncoder()
y_encoded = encoder.fit_transform(y)

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_encoded, test_size=0.2)

In [28]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(11720, 23)
(2931, 23)
(11720,)
(2931,)


In [29]:
rf_clf = RandomForestClassifier()
rf_clf.fit(X_train, y_train)

RandomForestClassifier()

In [30]:
y_pred = rf_clf.predict(X_test)

# Calculate metrics
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)


In [31]:
print(f'Random Forest Accuracy: {accuracy:.2f}')
print('Confusion Matrix:')
print(conf_matrix)
print('Classification Report:')
print(class_report)


Random Forest Accuracy: 0.89
Confusion Matrix:
[[968  24  14   0   4   8   0]
 [ 49 204  24   5  16   1   0]
 [ 31  12 291  16  34   2   0]
 [  3   0   6 151   1   1   0]
 [ 10   8  15   3 359   6   0]
 [ 10   1   8   0   8 100   0]
 [  2   6   6   0   2   0 522]]
Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.95      0.93      1018
           1       0.80      0.68      0.74       299
           2       0.80      0.75      0.78       386
           3       0.86      0.93      0.90       162
           4       0.85      0.90      0.87       401
           5       0.85      0.79      0.82       127
           6       1.00      0.97      0.98       538

    accuracy                           0.89      2931
   macro avg       0.87      0.85      0.86      2931
weighted avg       0.88      0.89      0.88      2931



In [32]:
class BayesianLinear(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()
        self.in_features = in_features
        self.out_features = out_features

        # Weight parameters
        self.weight_mu = nn.Parameter(torch.Tensor(out_features, in_features).uniform_(-0.2, 0.2))
        self.weight_rho = nn.Parameter(torch.Tensor(out_features, in_features).uniform_(-5, -4))

        # Bias parameters
        self.bias_mu = nn.Parameter(torch.Tensor(out_features).uniform_(-0.2, 0.2))
        self.bias_rho = nn.Parameter(torch.Tensor(out_features).uniform_(-5, -4))

    def forward(self, input):
        weight_sigma = torch.log1p(torch.exp(self.weight_rho))
        bias_sigma = torch.log1p(torch.exp(self.bias_rho))

        weight = Normal(self.weight_mu, weight_sigma).rsample()
        bias = Normal(self.bias_mu, bias_sigma).rsample()

        return F.linear(input, weight, bias)

class BayesianMLP(nn.Module):
    def __init__(self, input_size, hidden_size, num_classes):
        super().__init__()
        self.hidden1 = BayesianLinear(input_size, hidden_size)
        self.hidden2 = BayesianLinear(hidden_size, hidden_size)
        self.out = BayesianLinear(hidden_size, num_classes)

    def forward(self, x):
        x = F.relu(self.hidden1(x))
        x = F.relu(self.hidden2(x))
        return self.out(x)

In [33]:
X_train_tensor = torch.FloatTensor(X_train)
X_test_tensor = torch.FloatTensor(X_test)
y_train_tensor = torch.LongTensor(y_train)
y_test_tensor = torch.LongTensor(y_test)

# Define constants
input_size = 23
hidden_size = 128  # Increased hidden size
num_classes = len(torch.unique(y_train_tensor))

In [34]:
start_time = time.time()
model = BayesianMLP(input_size, hidden_size, num_classes)
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
criterion = nn.CrossEntropyLoss()

num_epochs = 100
batch_size = 32

for epoch in range(num_epochs):
    for i in range(0, len(X_train_tensor), batch_size):
        batch_X = X_train_tensor[i:i+batch_size]
        batch_y = y_train_tensor[i:i+batch_size]

        optimizer.zero_grad()
        outputs = model(batch_X)
        loss = criterion(outputs, batch_y)
        loss.backward()
        optimizer.step()

    if (epoch + 1) % 10 == 0:
        print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')
end_time = time.time()  # Record the end time
elapsed_time = end_time - start_time  # Calculate the elapsed time
print(f'Training completed in {elapsed_time:.2f} seconds')

Epoch [10/100], Loss: 1.0616
Epoch [20/100], Loss: 0.8813
Epoch [30/100], Loss: 0.8966
Epoch [40/100], Loss: 0.8159
Epoch [50/100], Loss: 0.7203
Epoch [60/100], Loss: 0.6850
Epoch [70/100], Loss: 0.7293
Epoch [80/100], Loss: 0.6723
Epoch [90/100], Loss: 0.6429
Epoch [100/100], Loss: 0.6015
Training completed in 60.26 seconds


In [166]:
model.eval()
with torch.no_grad():
    correct = 0
    total = 0
    outputs = model(X_test_tensor)
    _, predicted = torch.max(outputs.data, 1)
    total += y_test_tensor.size(0)
    correct += (predicted == y_test_tensor).sum().item()
    print(f'Accuracy on the test set: {100 * correct / total:.2f}%')

Accuracy on the test set: 80.62%


In [167]:
def instability_check(model, x, num_samples=2, threshold=0.1):
    model.eval()
    outputs = []

    for _ in range(num_samples):
        with torch.no_grad():
            outputs.append(F.softmax(model(x), dim=1))

    outputs = torch.stack(outputs)
    mean_output = outputs.mean(dim=0)

    js_divergence = 0.5 * F.kl_div(outputs[0].log(), mean_output, reduction='batchmean') + \
                    0.5 * F.kl_div(outputs[1].log(), mean_output, reduction='batchmean')

    instability = torch.sqrt(js_divergence)

    return instability.item() > threshold

In [168]:
def familiarity_based_filtering(model, X, lambda_factor=1.0, beta_2=0.5):
    model.eval()
    familiarities = []

    for x in X:
        x = x.unsqueeze(0)

        # Compute confidence
        with torch.no_grad():
            output = model(x)
        confidence = F.softmax(output, dim=1).max().item()

        # Compute instability
        instability = instability_check(model, x, num_samples=2, threshold=1.0)  # We want the actual value, not boolean

        # Compute familiarity
        familiarity = (lambda_factor * (confidence - beta_2) - instability) / np.sqrt(lambda_factor**2 + 1)
        familiarities.append(familiarity)

    familiarities = np.array(familiarities)

    # Filter packets with negative familiarity scores
    unknown_indices = np.where(familiarities < 0)[0]

    return unknown_indices, familiarities

In [169]:
def update_model(model, X_new, y_new, num_epochs=10, lr=0.001):
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    criterion = nn.CrossEntropyLoss()

    model.train()
    for epoch in range(num_epochs):
        optimizer.zero_grad()
        output = model(X_new)
        loss = criterion(output, y_new)
        loss.backward()
        optimizer.step()

        if (epoch + 1) % 5 == 0:
            print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

    return model

In [170]:
xnew1 = df2[df2.columns[:-1]]
ynew1 = df2['class1']

In [171]:
xnew1

duration  total_fiat  total_biat  min_fiat  min_biat       max_fiat  \
0      22930417          18           4  10995965  10960941  314115.301370   
1      25199304          16           4  11037969  10851858  359269.900000   
2      29772995          17           7   4093396   3956161  261815.256637   
3      29609149          22           6   3954677   3943698  271180.963303   
4       7863522          30           8   2067690   2068091  244213.125000   
...         ...         ...         ...       ...       ...            ...   
14646       332          -1          -1        -1        -1       0.000000   
14647       297          -1          -1        -1        -1       0.000000   
14648    251872          -1          -1        -1        -1       0.000000   
14649       304          -1          -1        -1        -1       0.000000   
14650       245          -1          -1        -1        -1       0.000000   

            max_biat     mean_fiat     mean_biat  flowPktsPerSecond  ...  \
0      360993.158730  1.306745e+06  1.389355e+06           6.018207  ...   
1      387414.676923  1.373362e+06  1.392885e+06           5.436658  ...   
2      310135.364583  6.445422e+05  6.512717e+05           7.086959  ...   
3      287136.446602  6.685474e+05  6.590460e+05           7.227496  ...   
4      252051.483871  5.718062e+05  5.628123e+05           8.266016  ...   
...              ...           ...           ...                ...  ...   
14646       0.000000  0.000000e+00  0.000000e+00        6024.096386  ...   
14647       0.000000  0.000000e+00  0.000000e+00        6734.006734  ...   
14648       0.000000  0.000000e+00  0.000000e+00           7.940541  ...   
14649       0.000000  0.000000e+00  0.000000e+00        6578.947368  ...   
14650       0.000000  0.000000e+00  0.000000e+00        8163.265306  ...   

        mean_flowiat    std_flowiat  min_active   mean_active  max_active  \
0      167375.306569  952994.511204     1491627  5.011278e+06    11141326   
1      185289.000000  976395.388090     1710925  4.164396e+06    14269600   
2      141776.166667  462297.947930     1363299  2.706523e+06     6192566   
3      139010.089202  472527.270988     1443143  2.937555e+06     4176130   
4      122867.531250  400581.170736     2092947  2.535199e+06     3282729   
...              ...            ...         ...           ...         ...   
14646     332.000000       0.000000          -1  0.000000e+00          -1   
14647     297.000000       0.000000          -1  0.000000e+00          -1   
14648  251872.000000       0.000000          -1  0.000000e+00          -1   
14649     304.000000       0.000000          -1  0.000000e+00          -1   
14650     245.000000       0.000000          -1  0.000000e+00          -1   

         std_active  min_idle     mean_idle  max_idle      std_idle  
0      4.507600e+06   1079974  3.668800e+06  10945954  4.855368e+06  
1      4.973926e+06   1234883  3.150269e+06  10851858  3.797336e+06  
2      1.445372e+06   1147658  1.955468e+06   3956161  8.938483e+05  
3      8.769669e+05   1065834  2.022585e+06   3895269  9.303813e+05  
4      6.509928e+05   1707343  1.897912e+06   2017289  1.667869e+05  
...             ...       ...           ...       ...           ...  
14646  0.000000e+00        -1  0.000000e+00        -1  0.000000e+00  
14647  0.000000e+00        -1  0.000000e+00        -1  0.000000e+00  
14648  0.000000e+00        -1  0.000000e+00        -1  0.000000e+00  
14649  0.000000e+00        -1  0.000000e+00        -1  0.000000e+00  
14650  0.000000e+00        -1  0.000000e+00        -1  0.000000e+00  

[14651 rows x 23 columns]

In [172]:
xnew1= scaler.fit_transform(xnew1)

In [173]:
X_new_tensor = torch.FloatTensor(xnew1)

In [174]:
y_new_encoded = encoder.fit_transform(ynew1)

In [175]:
y_new_tensor=torch.LongTensor(y_new_encoded)

In [176]:
np.unique(y_new_encoded)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [177]:
import time

In [178]:
start_time = time.time()
unknown_indices, familiarities = familiarity_based_filtering(model, X_new_tensor)
print(len(unknown_indices))
if len(unknown_indices) > 0:
    X_new = X_new_tensor[unknown_indices]
    y_new = y_new_tensor[unknown_indices]

    # Update X_train and y_train
    X_train = torch.cat([X_train_tensor, X_new], dim=0).numpy()
    y_train = torch.cat([y_train_tensor, y_new], dim=0).numpy()

    # Re-create tensors for updated X_train and y_train
    X_train_tensor = torch.FloatTensor(X_train)
    y_train_tensor = torch.LongTensor(y_train)
    num_classes = len(torch.unique(y_train_tensor))

#     # Update and re-train model
    model = BayesianMLP(input_size, hidden_size, num_classes)
    optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
    criterion = nn.CrossEntropyLoss()

    for epoch in range(num_epochs):
        for i in range(0, len(X_train_tensor), batch_size):
            batch_X = X_train_tensor[i:i+batch_size]
            batch_y = y_train_tensor[i:i+batch_size]

            optimizer.zero_grad()
            outputs = model(batch_X)
            loss = criterion(outputs, batch_y)
            loss.backward()
            optimizer.step()

        if (epoch + 1) % 10 == 0:
            print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

# Re-evaluate Bayesian model after update
model.eval()
with torch.no_grad():
    correct = 0
    total = 0
    outputs = model(X_test_tensor)
    _, predicted = torch.max(outputs.data, 1)
    total += y_test_tensor.size(0)
    correct += (predicted == y_test_tensor).sum().item()
end_time = time.time()  # Record the end time
elapsed_time = end_time - start_time  # Calculate the elapsed time
print(f'Training completed in {elapsed_time:.2f} seconds')

1306
Epoch [10/200], Loss: 4.0656
Epoch [20/200], Loss: 2.2345
Epoch [30/200], Loss: 3.8220
Epoch [40/200], Loss: 5.5306
Epoch [50/200], Loss: 5.1098
Epoch [60/200], Loss: 5.0822
Epoch [70/200], Loss: 3.9984
Epoch [80/200], Loss: 4.1985
Epoch [90/200], Loss: 3.8656
Epoch [100/200], Loss: 3.7298
Epoch [110/200], Loss: 3.3857
Epoch [120/200], Loss: 4.0028
Epoch [130/200], Loss: 4.9153
Epoch [140/200], Loss: 3.8250
Epoch [150/200], Loss: 3.1200
Epoch [160/200], Loss: 3.4478
Epoch [170/200], Loss: 2.4737
Epoch [180/200], Loss: 3.2963
Epoch [190/200], Loss: 3.2986
Epoch [200/200], Loss: 1.5096
Training completed in 163.85 seconds


In [179]:
start_time = time.time()
rf_clf = RandomForestClassifier()
rf_clf.fit(X_train, y_train)

# Evaluate the RandomForest model
y_pred = rf_clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f'Random Forest Accuracy: {accuracy:.2f}')
print('Confusion Matrix:')
print(confusion_matrix(y_test, y_pred))
end_time = time.time()  # Record the end time
elapsed_time = end_time - start_time  # Calculate the elapsed time
print(f'Training completed in {elapsed_time:.2f} seconds')

Random Forest Accuracy: 0.86
Confusion Matrix:
[[943  21   8   0   3   2   1  66   1   0   0   0   0]
 [ 36 167  26   2   5   2   2   0  16   0   0   0   0]
 [ 34  11 319  12   8   2   1   0   0  19   0   0   0]
 [  0   2   3 153   0   0   0   0   0   0  19   0   0]
 [ 13   7  54   0 267   6   0   0   0   0   0   9   0]
 [  2   1  11   0   4 115   0   0   0   0   0   0   0]
 [  2   0   4   0   0   0 551   0   0   0   0   0   1]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0]]
Training completed in 2.44 seconds


In [180]:
X_train.shape

(13026, 23)

In [181]:
y_train.shape

(13026,)

In [182]:
xnew1.shape

(14651, 23)

In [183]:
y_new_encoded.shape

(14651,)

In [184]:
y_pred = rf_clf.predict(xnew1)

In [185]:
y_pred.shape

(14651,)

In [186]:
y_new_encoded

array([1, 1, 1, ..., 4, 4, 4])

In [187]:
accuracy = accuracy_score(y_new_encoded, y_pred)

In [188]:
print(f'Random Forest Accuracy: {accuracy:.2f}')

Random Forest Accuracy: 0.48
